# Generated by Django 4.2.5 on 2023-09-19 14:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_id', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('custom_url', models.URLField(blank=True, null=True)),
                ('default_language', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('view_count', models.BigIntegerField(default=0)),
                ('subscriber_count', models.BigIntegerField(default=0)),
                ('hidden_subscriber_count', models.BooleanField(default=False)),
                ('video_count', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('I', 'Initialized'), ('S', 'Scraping'), ('D', 'Scraped'), ('F', 'Failed')], default='I', max_length=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_id', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_language', models.CharField(blank=True, max_length=200, null=True)),
                ('category_id', models.CharField(blank=True, max_length=200, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.BigIntegerField(default=0)),
                ('like_count', models.BigIntegerField(default=0)),
                ('dislike_count', models.BigIntegerField(default=0)),
                ('favorite_count', models.BigIntegerField(default=0)),
                ('comment_count', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('I', 'Initialized'), ('S', 'Scraping'), ('D', 'Scraped'), ('F', 'Failed')], default='I', max_length=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='scrapper.channel')),
            ],
        ),
        migrations.CreateModel(
            name='BrandDeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_deals', to='scrapper.brand')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_deal_links', to='scrapper.video')),
            ],
        ),
    ]
