# Generated by Django 4.2.5 on 2023-09-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('S', 'Scraped'), ('D', 'Detailed'), ('F', 'Filtered'), ('K', 'Skipped')], default='S', max_length=1),
        ),
    ]
