# Generated by Django 4.2.5 on 2023-09-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_remove_channel_status_alter_branddeal_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='default_language',
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
