# Generated by Django 4.2.5 on 2023-09-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0003_remove_channel_default_language_alter_video_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='dislike_count',
        ),
    ]
