# Generated by Django 4.2.5 on 2023-09-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0005_rename_url_branddeal_initial_url_branddeal_final_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='status',
            field=models.CharField(choices=[('C', 'Created'), ('D', 'Detailed')], default='C', max_length=1),
        ),
    ]
