# Generated by Django 4.2.5 on 2023-09-22 07:04

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0007_alter_video_options_video_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 9, 22, 7, 3, 57, 960908, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branddeal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='has_cross_scraped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='status',
            field=models.CharField(choices=[('C', 'Created'), ('P', 'Processing'), ('A', 'Paused'), ('O', 'Completed')], default='C', max_length=1),
        ),
    ]
