# Generated by Django 4.2.5 on 2023-09-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0008_brand_created_at_branddeal_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='status',
            field=models.CharField(choices=[('C', 'Created'), ('F', 'Fetched'), ('P', 'Processing'), ('A', 'Paused'), ('O', 'Completed')], default='C', max_length=1),
        ),
    ]
