# Generated by Django 4.2.5 on 2023-09-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0012_blacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='branddeal',
            name='page_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
