# Generated by Django 4.2.5 on 2023-09-24 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0013_branddeal_page_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='has_cross_scraped',
        ),
    ]
