# TOTAL_CHANNELS_COUNT = 1000
# CHANNEL_IGNORE_VIDEO_COUNT = 1500
# CHANNEL_VIDEOS_FETCH_COUNT = 500
# TODO

TOTAL_CHANNELS_COUNT = 30
CHANNEL_IGNORE_VIDEO_COUNT = 1500
CHANNEL_VIDEOS_FETCH_COUNT = 50
